Gamificacion/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('registration/', views.registration, name='registration'),
    path('cuestionario/', views.questionary, name='questionary'),
    path('obtener-preguntas/', views.questions, name='obtener-preguntas'),
    path('enviar-resultados/', views.sendResults, name='enviar-resultados'),
    path('resultados/', views.finalResults, name='resultados'),
    path('detalles-de-carreras/', views.careerDetails, name='detalles-de-carreras'),
    path('funcion-de-calculo/', views.aboutCalculationFunction, name='funcion-de-calculo'),
    path('detalles-de-rasgos-de-personalidad/', views.userTraitDetails, name='detalles-de-rasgos-de-personalidad')
]

Tesis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Gamificacion.urls'))
]

Gamificacion/models.py
from django.db import models

# Create your models here.

Gamificacion/forms.py
from django import forms

class RegistrationForm(forms.Form):
    avatar = forms.ChoiceField(choices=[('bob', 'Bob'), ('alice', 'Alice')])
    userName = forms.CharField(max_length=100)

Gamificacion/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .forms import *
import random

# Diccionario de carreras
careers = {
    'Economía': ['Apertura a la experiencia', 'Conciencia', 'Amabilidad', 'Extraversión'],
    'Contador Público Nacional': ['Conciencia', 'Amabilidad'],
    'Derecho': ['Conciencia', 'Amabilidad', 'Extraversión'],
    'Notariado': ['Conciencia', 'Amabilidad'],
    'Medicina': ['Conciencia', 'Amabilidad', 'Neuroticismo'],
    'Enfermería': ['Amabilidad', 'Neuroticismo'],
    'Odontología': ['Conciencia', 'Amabilidad'],
    'Kinesiología y Fisioterapia': ['Amabilidad', 'Extraversión', 'Conciencia'],
    'Bioquímica': ['Apertura a la experiencia', 'Conciencia', 'Amabilidad'],
    'Química y Farmacia': ['Conciencia', 'Amabilidad'],
    'Psicología': ['Amabilidad', 'Conciencia'],
    'Ingeniería Informática': ['Apertura a la experiencia', 'Conciencia', 'Extraversión'],
    'Ingeniería Industrial': ['Apertura a la experiencia', 'Conciencia', 'Extraversión'],
    'Ingeniería Química': ['Apertura a la experiencia', 'Conciencia', 'Amabilidad']
}

careersInformation = [
    {
        "carrera": "Economía",
        "titulo": "Licenciado en Economía",
        "duracion": "5 años",
        "descripcion": "El licenciado en Economía es un experto en ciencias económicas con formación académica y técnica, "
            "capaz de analizar y asesorar en economía a nivel nacional e internacional, con un enfoque ético y compromiso con el desarrollo social. "
            "Está preparado para tomar decisiones económicas importantes y para continuar su formación en estudios superiores.",
        "img": "/static/img/avatar-carreras/economia-avatar.png"
    },
    {
        "carrera": "Contador Público Nacional",
        "titulo": "Contador Público Nacional",
        "duracion": "4 años",
        "descripcion": "El Contador Público Nacional está formado ética y críticamente en contabilidad y ciencias económicas, preparado para resolver problemas complejos, "
            "aprender continuamente y liderar en entornos organizacionales a nivel local e internacional, en áreas como finanzas, fiscalidad, auditoría y responsabilidad social y ambiental.",
        "img": "/static/img/avatar-carreras/contador-avatar.png"
    },
    {
        "carrera": "Derecho",
        "titulo": "Abogado/a",
        "duracion": "5 años",
        "descripcion": "El abogado está capacitado en ciencias jurídicas para interpretar y aplicar el Derecho, y puede trabajar en la función pública, "
            "ejercer la abogacía o ser Consultor Jurídico en el sector público, privado o mixto.",
        "img": "/static/img/avatar-carreras/derecho-avatar.png"
    },
    {
        "carrera": "Notariado",
        "titulo": "Notario",
        "duracion": "4 años",
        "descripcion": "El notario es un profesional en ciencias jurídicas, especializado en derecho notarial y asistencia jurídica, "
            "capacitado para trabajar en registros públicos, la función pública y como consultor jurídico en diversos sectores.",
        "img": "/static/img/avatar-carreras/notariado-avatar.png"
    },
    {
        "carrera": "Medicina",
        "titulo": "Médico Cirujano",
        "duracion": "7 años",
        "descripcion": "El egresado de la carrera de Medicina es un profesional generalista del área de la salud, capacitado para atender las necesidades de salud prevalentes "
            "y las urgencias no derivables de la población, con principios éticos, sentido de responsabilidad social y comprometido para gerenciar su formación médica continua.",
        "img": "/static/img/avatar-carreras/medicina-avatar.png"
    },
    {
        "carrera": "Enfermería",
        "titulo": "Licenciado/a en Enfermería",
        "duracion": "4 años",
        "descripcion": "El egresado de la carrera de Enfermería podrá identificar y resolver problemas de salud, ejercer como enfermero generalista o especializado, "
            "promover la salud pública y administrar servicios de enfermería, optimizando los recursos disponibles.",
        "img": "/static/img/avatar-carreras/enfermeria-avatar.png"
    },
    {
        "carrera": "Odontología",
        "titulo": "Odontólogo/a",
        "duracion": "5 años",
        "descripcion": "El egresado de la carrera de Odontología es un profesional capacitado para prevenir, diagnosticar, tratar y recuperar la salud bucal del individuo "
            "con calidad y calidez, aplicando principios científicos, éticos, socio humanísticos y capaz de gerenciar su formación contínua.",
        "img": "/static/img/avatar-carreras/odontologia-avatar.png"
    },
    {
        "carrera": "Kinesiología y Fisioterapia",
        "titulo": "Licenciado en Kinesiología y Fisioterapia",
        "duracion": "5 años",
        "descripcion": "El Kinesiólogo Fisioterapeuta podrá desarrollar las actividades dependiendo donde esté, con las competencias y habilidades "
            "para una remuneración adecuada a la formación profesional recibida. Puede desempeñarse en áreas de la salud del ámbito público y privado "
            "como hospitales y centros de salud, centros de rehabilitación y recuperación, centros de investigaciones científicas. Asimismo en el área de deportes "
            "cómo organizaciones deportivas, preparación psico- física y orientación y supervisores de gimnasios.",
        "img": "/static/img/avatar-carreras/kinesiologia-avatar.png"
    },
    {
        "carrera": "Bioquímica",
        "titulo": "Bioquímico/a",
        "duracion": "5 años",
        "descripcion": "El bioquímico es un profesional con sólidos conocimientos científicos,  prácticos y éticos con una formación integral cristiana, "
            "que le permitirá desarrollar sus actividades en el ámbito de la salud y la investigación, en el contexto nacional e internacional. El mismo será capaz de diseñar, "
            "ejecutar, científica, técnica y éticamente pruebas de laboratorio basadas en métodos físicos, químicos y biológicos, a partir de muestras clínicas, toxicológicas, "
            "forenses, alimentarias y biotecnológicas. Además, puede ejercer la dirección técnica de un laboratorio, también manejar con criterios de bioseguridad materiales "
            "peligrosos de origen biológico, radiactivo y químico.",
        "img": "/static/img/avatar-carreras/bioquimica-avatar.png"
    },
    {
        "carrera": "Química y Farmacia",
        "titulo": "Químico/a Farmacéutico/a",
        "duracion": "5 años",
        "descripcion": "El Químico Farmacéutico es el profesional de la salud con sólida formación científico-humanista-cristiana y tecnológica que le permite liderar, innovar, "
            "emprender y comprometerse socialmente en el mantenimiento de la salud y de la calidad de vida de la población. Es experto en medicamentos, cosméticos, productos afines "
            "y otras sustancias químicas relacionadas. Está capacitado para realizar responsablemente el diseño, evaluación, desarrollo, producción, control, distribución, gestión "
            "de calidad y promoción del uso racional del medicamento.",
        "img": "/static/img/avatar-carreras/quimicaFarmacia-avatar.png"
    },
    {
        "carrera": "Psicología",
        "titulo": "Lic. en Psicología Clínica",
        "duracion": "5 años",
        "descripcion": "El psicólogo es un profesional que tiene las competencias para diagnosticar e intervenir en el área del ejercicio de la Psicología, con las técnicas y los instrumentos "
            "proporcionados por la Ciencia Psicológica. El profesional podrá desempeñarse en el área clínica como educacional.",
        "img": "/static/img/avatar-carreras/psicologia-avatar.png"
    },
    {
        "carrera": "Ingeniería Informática",
        "titulo": "Ingeniero Informático",
        "duracion": "5 años",
        "descripcion": "El Ingeniero Informático es un profesional capacitado para el manejo de los recursos informáticos. Instrumenta, analiza y diseña sistemas de información que permitirán el "
            "desarrollo integral de las organizaciones. Además, puede realizar tareas como estudio de factibilidad técnico económico para el desarrollo de software y redes, montaje y mantenimiento de "
            "sistemas informáticos. Asimismo, puede desempeñarse en empresas de desarrollo de software, área de las telecomunicaciones, instituciones públicas y privadas, financieras, industrias y empresas.",
        "img": "/static/img/avatar-carreras/ingenieriaInformatica-avatar.png"
    },
    {
        "carrera": "Ingeniería Química",
        "titulo": "Ingeniero Químico",
        "duracion": "5 años",
        "descripcion": "El Ingeniero Químico es un profesional que conoce los fundamentos de las ciencias básicas y las ciencias naturales, de las operaciones unitarias y de los procesos químicos, "
            "con la finalidad de efectuar la transformación de la materia prima y energía en productos terminados, empleando “tecnologías limpias” y cuidando la economía de los procesos. Además, "
            "puede realizar tareas como la construcción, montaje de equipos y plantas, control de producción y control ambiental. Asimismo, puede desempeñarse en sectores de industrias químicas y petroquímicas, "
            "alimentos y bebidas, biotecnología, generación de energía y farmacéutica.",
        "img": "/static/img/avatar-carreras/ingenieriaQuimica-avatar.png"
    },
    {
        "carrera": "Ingeniería Industria",
        "titulo": "Ingeniero Industrial",
        "duracion": "5 años",
        "descripcion": "Los/as ingenieros/as industriales son profesionales que permiten el desarrollo sustentable de la industria, contemplando la variable ambiental en el proceso. "

Gamificacion/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Mi Vocación Ideal</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'img/logo-white.png' %}" alt="Logo" width="170">
            </a>
            <div class="ml-auto d-flex flex-grow-1 justify-content-end align-items-center">
                <a class="btn btn-outline-secondary btn-sm nav-btn me-2" href="{% url 'home' %}">
                    <i class="bi bi-house"></i> Inicio
                </a>
                <a class="btn btn-outline-secondary btn-sm nav-btn" href="{% url 'funcion-de-calculo' %}">
                    <i class="bi bi-info-circle"></i> Acerca de
                </a>
            </div>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
    <footer class="footer"><p>&copy; {% now "Y" %} | Mi vocación ideal<br>Desarrollado por Gerardo Espínola</p></footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

Gamificacion/templates/detalles-de-carreras.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section>
    <div class="container">
        <br>
        <div class="alert alert-warning rounded">
            <h3 class="custom-title">ATENCIÓN ⚠️</h3>
            <p class="custom-title">
                Esta aplicación no es una guía definitiva para la elección de una carrera universitaria, 
                está creada nada más con fines académicos, basadas en los rasgos de personalidad del modelo OCEAN con algunas carreras de referencias.
            </p>
        </div>
        <hr>
        <h2 class="custom-title">Detalles de carreras sugeridas:</h2>
        <ul>
            {% for career in career_details %}
                <li>
                    <div class="row" style="padding-top: 1%;">
                        <div class="col-auto">
                            <img src="{{ career.avatar }}" alt="Avatar de carrera" style="filter:drop-shadow(3px 5px 3px rgba(0, 0, 0, 0.2)); width: 300px; padding: 2%;">
                        </div>
                        <div class="col">
                            <strong>{{ career.carrera }}</strong>
                            <p>Título: {{ career.titulo }}</p>
                            <p>Duración: {{ career.duracion }}</p>
                            <p>Descripción: {{ career.descripcion }}</p>
                            <p>
                                Fuente: 
                                <a href="https://guaira.uc.edu.py" target="_blank">Página Web UC Guairá</a>.
                            </p>
                        </div>
                    </div>
                    <hr>
                </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

Gamificacion/templates/detalles-de-rasgos.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section>
    <div class="container">
        <br>
        <div class="alert alert-warning rounded">
            <h3 class="custom-title">ATENCIÓN ⚠️</h3>
            <p class="custom-title">
                Esta aplicación no es una guía definitiva para la elección de una carrera universitaria, 
                está creada nada más con fines académicos, basadas en los rasgos de personalidad del modelo OCEAN con algunas carreras de referencias.
            </p>
        </div>
        <hr>
        <h2 class="custom-title">{{userName}}, las carreras sugeridas fueron seleccionadas en base a los rasgos de personalidad según tu puntuación:</h2>
        <div class="row">
            {% for career, traits in suggestedCareers.items %}
                <p>✔️ {{ career }}: {{ traits|join:", " }}</p>
            {% endfor %}    
        </div>
        <hr>
        <h2 class="custom-title">Estos son los detalles de los rasgos de personalidad basados en tu puntuación:</h2>
        <div class="mt-3">
            {{ html_content|safe }}
        </div>
        <hr>
        <p class="custom-title">¿Quieres conocer más sobre la aplicación y su funcionalidad?</p>
        <div style="display: flex; justify-content: center; align-items: center;">
            <a class="btn btn-success custom-btn" href="{% url 'funcion-de-calculo' %}">Ver más</a>
        </div>
        <br>
    </div>
</section>
{% endblock %}

Gamificacion/templates/funcion-de-calculo.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section>
    <div class="container">
        <div class="d-flex flex-column align-items-center">
            <img src="{% static 'img/avatar-duda.png' %}" alt="Duda sobre función de cálculo" class="img-fluid">
        </div>
        <br>
        <div class="alert alert-warning rounded">
            <h3 class="custom-title">ATENCIÓN ⚠️</h3>
            <p class="custom-title">
                Esta aplicación no es una guía definitiva para la elección de una carrera universitaria, 
                está creada nada más con fines académicos, basadas en los rasgos de personalidad del modelo OCEAN con algunas carreras de referencias.
            </p>
        </div>
        <hr>
        <h2 class="custom-title" style="padding: 3%;">Explicación de la función de cálculo de carreras universitarias 🤓</h2>
        <hr>
        <div style="font-size: 18px;">
            <p>
                La aplicación cuenta con un mecanismo que ayuda a elegir una carrera universitaria, basándose en las respuestas del cuestionario. 
                Las preguntas tienen relación con los rasgos de personalidad del modelo OCEAN: 
                <ul>
                    <li>☑️ Apertura a la experiencia: Imaginativo, creativo, curioso, artístico, explorador, abierto.</li>
                    <li>☑️ Conciencia: Organizado, responsable, disciplinado, confiable, cuidadoso.</li>
                    <li>☑️ Extraversión: Sociable, enérgico, activo, comunicativo, amigable, extrovertido.</li>
                    <li>☑️ Amabilidad: Compasivo, empático, cooperativo, amable, generoso.</li>
                    <li>☑️ Neuroticismo: Ansioso, inseguro, inestable, irritable, preocupado, nervioso.</li>
                </ul>
                y por cada pregunta respondida en la escala de acuerdo/desacuerdo se almacena una puntuación en cada rasgo de personalidad.
            </p>
            <p>
                Además, la aplicación cuenta con una lista de carreras universitarias, donde cada carrera está asociada a uno o más rasgos de personalidad:
                <ul>
                    <li>✅ Economía: Apertura a la experiencia, Conciencia, Amabilidad y Extraversión.</li>
                    <li>✅ Contador Público Nacional: Conciencia y Amabilidad.</li>
                    <li>✅ Derecho: Conciencia, Amabilidad y Extraversión.</li>
                    <li>✅ Notariado: Conciencia y Amabilidad.</li>
                    <li>✅ Medicina: Conciencia, Amabilidad y Neuroticismo</li>
                    <li>✅ Enfermería: Amabilidad y Neuroticismo.</li>
                    <li>✅ Odontología: Conciencia y Amabilidad.</li>
                    <li>✅ Kinesiología y Fisioterapia: Amabilidad, Extraversión y Conciencia.</li>
                    <li>✅ Bioquímica: Apertura a la experiencia, Conciencia y Amabilidad.</li>
                    <li>✅ Química y Farmacia: Conciencia y Amabilidad.</li>
                    <li>✅ Psicología: Amabilidad y Conciencia.</li>
                    <li>✅ Ingeniería Informática: Apertura a la experiencia, Conciencia y Extraversión.</li>
                    <li>✅ Ingeniería Química: Apertura a la experiencia, Conciencia y Amabilidad.</li>
                    <li>✅ Ingeniería Industrial: Apertura a la experiencia, Conciencia y Extraversión. </li>
                </ul>
                Seguidamente se calcula una puntuación para cada carrera con sus rasgos asociados a partir de la suma de los valores por rasgos obtenidos en el cuestionario.
            </p>
            <p>
                Finalmente, se muestran las carreras con mayor puntuación conforme al cálculo realizado.
            </p>
        </div>
    </div>
</section>
{% endblock %}

Gamificacion/templates/home.html
{% extends "base.html"%}
{% load static %}
{% block content%}
<section>
    <div class="container">
        <div class="row">
            <div class="col-md d-flex align-items-center">
                <img src="{% static 'img/background.png' %}" alt="Mi Vocación Ideal" class="img-fluid">
            </div>
            <div class="col-md d-flex align-items-center">
                <div class="text-center">
                    <br>
                    <h1 class="custom-title">¡Descubre tu vocación <br>de una forma divertida y gratis!</h1>
                    <a class="btn btn-success custom-btn" href="{% url 'registration' %}">Empezar ahora</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

Gamificacion/templates/questionary.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section id="questionSection">
    <div class="d-flex flex-column align-items-center m-3">
        <img src="{{avatar}}" alt="Avatar del usuario" style="width: 100px;">
        <h2 class="custom-title" style="padding-top: 1%;">¡Hola {{userName}}!</h2>
    </div>
    <div class="container">
        <div class="row" style="text-align: right;">
            <img src="{% static 'img/sin-estrellas.png' %}" id="starimg" data-star1="{% static 'img/1-estrella.png' %}" data-star2="{% static 'img/2-estrellas.png' %}" data-star3="{% static 'img/3-estrellas.png' %}" alt="Sin estrellas" style="width: 120px; display: block; margin-left: auto;">
        </div>
        <div class="container mt-1">
            <p>Tu progreso:</p>
            <div class="progress progress-color-transition">
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-success" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
        </div>
    </div>

    <div class="container mt-5">
        <h2 class="custom-title" id="question"></h2>
        <br>
        <div class="likert-scale">
            <div class="likert-item">
                <input type="radio" id="likert1" name="likert" value="1">
                <label for="likert1">Totalmente en desacuerdo</label>
            </div>
            <div class="likert-item">
                <input type="radio" id="likert2" name="likert" value="2">
                <label for="likert2">En desacuerdo</label>
            </div>
            <div class="likert-item">
                <input type="radio" id="likert3" name="likert" value="3">
                <label for="likert3">Neutral</label>
            </div>
            <div class="likert-item">
                <input type="radio" id="likert4" name="likert" value="4">
                <label for="likert4">De acuerdo</label>
            </div>
            <div class="likert-item">
                <input type="radio" id="likert5" name="likert" value="5">
                <label for="likert5">Totalmente de acuerdo</label>
            </div>
        </div>
        <div class="next-btn">
            <button type="button" class="btn btn-success custom-btn" id="nextBtn" disabled>Siguiente</button>
        </div>
        <br>
    </div>
</section>
<section id="loaderSection" style="display: none;">
    <div id="loader" class="loader"></div>
</section>
{% endblock %}

Gamificacion/templates/registration.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section>
    <div class="container">
        <div class="row" style="padding: 10px;">
            <h2 class="custom-title">¡Regístrate para iniciar el test!</h2>
        </div>
        <div class="row justify-content-center" style="padding: 5%;">
            <form method="post">
                {% csrf_token %}
                <div class="form-group text-center">
                    <p class="custom-title">Selecciona tu avatar</p>
                    <div class="row justify-content-center">
                        <div class="col-md-3">
                            <div class="d-flex flex-column align-items-center">
                                <img src="{% static 'img/bob-avatar.png' %}" alt="Bob" width="170px">
                                <label class="form-check-label mt-2" for="id_avatar_bob">
                                    <input class="form-check-input" type="radio" id="id_avatar_bob" name="avatar" value="bob"> Bob
                                </label>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="d-flex flex-column align-items-center">
                                <img src="{% static 'img/alice-avatar.png' %}" alt="Alice" width="170px">
                                <label class="form-check-label mt-2" for="id_avatar_alice">
                                    <input class="form-check-input" type="radio" id="id_avatar_alice" name="avatar" value="alice"> Alice
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group text-center" style="padding: 3%;">
                    <label for="id_userName" style="padding-bottom: 3%;">Ingresa tu nombre:</label>
                    <div class="input-group justify-content-center">
                        <input type="text" class="form-control" id="id_userName" name="userName" placeholder="Ingresa tu nombre" style="max-width: 400px;">
                    </div>
                </div>
                <div class="form-group text-center">
                    <button type="submit" class="btn btn-primary custom-btn">Siguiente</button>
                </div>
            </form>
        </div>
        {% if form.errors %}
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-danger" role="alert">
                    <strong>Error:</strong>
                    Los campos no pueden quedar vacíos, por favor complete los mismos.
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

Gamificacion/templates/results.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section>
    <div class="container">
        <div id="results-section" style="background-color: #e4e4e4;">
            <div class="d-flex flex-column align-items-center m-3">
                <img src="{{userAvatar}}" alt="Avatar del usuario" style="width: 100px;">
                <h1 class="custom-title">¡Felicidades <span id="userNameSpan">{{userName}}</span>!</h1>
            </div>
            <h5 class="custom-title">Has culminado el test satisfactoriamente. En base a tus resultados te recomendamos estas carreras:</h5>
            <div class="mt-2 d-flex justify-content-center">
                <ul class="list-unstyled d-flex flex-wrap justify-content-center align-items-center career-list">
                    {% for career in careerDetails %}
                    <li class="career-item d-flex flex-column align-items-center m-3">
                        <img src="{{ career.avatar }}" alt="Avatar de carrera" style="filter: drop-shadow(3px 5px 3px rgba(0, 0, 0, 0.2)); width: 300px; padding: 1%;">
                        <h5 class="custom-title" style="font-weight: bold;">{{ career.carrera }}</h5>
                    </li>
                    {% endfor %}
                </ul>
            </div>            
        </div>
        <p class="custom-title">¿Quieres compartir los resultados con tus amigos?</p>
        <div class="text-center mt-4">
            <button type="button" class="btn btn-success btn-sm" id="captureBtn"><i class="bi bi-download"></i> Descargar Resultados</button>
        </div>
        <br>
        {% if careerDetails %}
            <p class="custom-title">¿Quieres conocer más detalles sobre las carreras?</p>
            <div style="display: flex; justify-content: center; align-items: center;">
                <a class="btn btn-success custom-btn" href="{% url 'detalles-de-carreras' %}">Explorar carreras</a>
            </div>
            <hr>
            <p class="custom-title">¿Quieres conocer más detalles sobre los rasgos de personalidad que presentas?</p>
            <div style="display: flex; justify-content: center; align-items: center;">
                <a class="btn btn-success custom-btn" href="{% url 'detalles-de-rasgos-de-personalidad' %}">Explorar detalles</a>
            </div>
            <br>
        {% endif %}
    </div>
</section>
<script>
    // compartir resultados
    document.getElementById('captureBtn').addEventListener('click', function() {
        var resultsSection = document.getElementById('results-section');
        var userName = document.getElementById('userNameSpan').textContent;

        // Capturar la imagen de la sección
        html2canvas(resultsSection).then(function(canvas) {
            var imgData = canvas.toDataURL('image/png');
            var link = document.createElement('a');
            link.href = imgData;
            link.download = 'Resultados-' + userName + '.png';
            link.click();
        });
    });
</script>
{% endblock %}